### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by imagejan** [quantixed/imagej-macros#10]
Thanks for sharing your tools and adding your update site, @quantixed !

For inspiration, you might want to check out the following projects that offer similar functionality:

1. Figures
    * [MagicMontage](http://imagejdocu.tudor.lu/doku.php?id=video:utilities:creating_montages_with_magic_montage)
    * [FigureJ](http://imagejdocu.tudor.lu/doku.php?id=plugin:utilities:figurej:start)
    * [ScientiFig](https://grr.gred-clermont.fr/labmirouse/software/)

2. Blind Experiment
    I created [this plugin](https://github.com/imagejan/imagej-plugins/blob/master/Blind_Experiment/src/main/java/imagejan/plugins/Blind_Experiment.java) a while ago (release is [here](https://github.com/imagejan/imagej-plugins/releases)). It is supposed to work well with any file type.

If these tools are interesting for you, or you're missing some functionality, it would be great to discuss on the [forum](http://forum.imagej.net/) how to make them more accessible and useful for the community.

**Comment by quantixed** [comment]
Hi @imagejan 

I didn't know about your **Blind Experiment** plugin. That is very nice indeed.

The Figure creation projects you have suggested are nice but none of them did what I wanted (I am quite particular about how multi-channel montages are presented), so I decided to write my own. I can definitely make my code more robust by looking closely at how they work.
