### ISSUE TITLE
Blind Analysis not running

### ISSUE THREAD

**Issue by mshand22** [quantixed/imagej-macros#15]
I successfully used blind analysis last week. 
I tried to run it today on my new images, similar but different folder location and it won't rename any image. 
I keep getting this error message, but whenever I try to reload the macro, it gives me a different blind number error (assuming with randomisation). 
All files are TIFFs, Fiji did update this morning right before I used it so something may have gone wrong there? 
I really don't understand coding so have no idea where to start looking

(Note, I have now removed spaces from folder names in case that was an issue for some reason, it didn't help)

![Screenshot 2022-02-08 at 10 43 41](https://user-images.githubusercontent.com/99255504/152974694-37b9a174-9244-43fa-9423-971a4335904f.png)

**Comment by quantixed** [comment]
Hello @mshand22 I think the problem is the dot (period) in the folder name `P8 and P.End `

Please can you try removing the dot and see whether it works?

**Comment by mshand22** [comment]
....yep it does not like the dots in the folder names

Thank you so much 

(I was close to breaking point with this)
